version: "3.1"
services:
  checkout:
    image: checkout
    build: ./checkout/
    environment:
      - "GRPC_PORT=8080"
      - "HTTP_PORT=8180"
      - "SERVICES_LOMS_URL=loms:8081"
      - "SERVICES_PRODUCT_SERVICE_URL=route256.pavl.uk:8082"
      - "SERVICES_PRODUCT_SERVICE_TOKEN=${PRODUCT_SERVICE_TOKEN}"
    ports:
      - "8080:8080"
      - "8180:8180"
  loms:
    image: loms
    build: ./loms/
    environment:
      - "GRPC_PORT=8081"
      - "HTTP_PORT=8181"
    ports:
      - "8081:8081"
      - "8181:8181"
  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
  test:
    image: test
    build: ./test/
    environment:
      - "SERVICES_CHECKOUT_URL=checkout:8080"
      - "SERVICES_LOMS_URL=loms:8081"
    depends_on:
      - checkout
      - loms
