version: "3.1"
services:
  checkout:
    image: checkout
    build: ./checkout/
    environment:
      - "HTTP_LISTEN=:8080"
      - "SERVICES_LOMS_URL=http://loms:8081"
      - "SERVICES_PRODUCT_SERVICE_URL=http://route256.pavl.uk:8080"
      - "SERVICES_PRODUCT_SERVICE_TOKEN=${PRODUCT_SERVICE_TOKEN}"
    ports:
      - "8080:8080"
  loms:
    image: loms
    build: ./loms/
    environment:
      - "HTTP_LISTEN=:8081"
    ports:
      - "8081:8081"
  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
