global:
  scrape_interval: 2s
  scrape_timeout: 2s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: "app"
    static_configs:
      - targets:
          - "checkout:8180" # checkout
          - "loms:8181" # loms
