// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IMessanger is an autogenerated mock type for the IMessanger type
type IMessanger struct {
	mock.Mock
}

// Send provides a mock function with given fields: msg
func (_m *IMessanger) Send(msg string) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIMessanger creates a new instance of IMessanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMessanger(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMessanger {
	mock := &IMessanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
